### ISSUE TITLE
Response is not Logging into Moesif

### ISSUE THREAD

**Issue by abhijithmjayan** [Moesif/moesif-netcore-example#19]
When I run this example its not returning any data but getting status 200. But that is not shown in moesif dashboard. But all the 404 response are logging into moesif.

**Comment by dgilling** [comment]
Hi @abhijithmjayan, let us take a look and understand why you're not seeing 200's logged or responded correctly. Can you provide some more info on which .NET Core version and example are you running?

**Comment by abhijithmjayan** [comment]
@dgilling  Thank you for your response. I fixed this issue with following configuration Settings. 
services.Configure<IISServerOptions>(config =>
            {
                config.AllowSynchronousIO = true;
            });
